language: node_js

notifications:
  slack: sytwull:1W2xlnDCFR0EYEUbKUFcDwJj

node_js:
  - "8"
dist: trusty
sudo: false

cache:
  directories:
    - node_modules

addons:
  chrome: stable

script:
  - cd ./DateMaker
  - npm install
  - npm run lint
  - npm run test:headless
  - npm run build
  - npm run e2e